[package]
name = "core"
version = "0.1.0"
edition = "2024"
license.workspace = true

[dependencies]
bevy = { version = "0.16.1", default-features = false }
osm_overpass = { workspace = true }
serde = { version = "1.0.219" }
toml = { version = "0.9.2" }
